'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { getCurrentUser } from '@/lib/auth';
import { Button } from '@/components/ui/button';
import {
  Sparkles,
  Code,
  Trophy,
  GraduationCap,
  BarChart3,
  ArrowRight,
  Zap,
  BookOpen,
  Terminal,
} from 'lucide-react';

export default function HomePage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadUser();
  }, []);

  const loadUser = async () => {
    try {
      const currentUser = await getCurrentUser();
      setUser(currentUser);
    } catch {
      setUser(null);
    } finally {
      setLoading(false);
    }
  };

  const features = [
    {
      icon: <Sparkles className="h-5 w-5 text-purple-600" />,
      title: 'AI-Powered Quizzes',
      description: 'Dynamic quizzes generated by AI, adapting to your skill level in real time.',
    },
    {
      icon: <Terminal className="h-5 w-5 text-purple-600" />,
      title: 'Hands-On Practice',
      description: 'Use the coding workspace, run solutions, and receive instant feedback.',
    },
    {
      icon: <Trophy className="h-5 w-5 text-purple-600" />,
      title: 'Ranked Leaderboard',
      description: 'Earn XP, improve your rank, and climb the global leaderboard.',
    },
    {
      icon: <BookOpen className="h-5 w-5 text-purple-600" />,
      title: 'Structured Paths',
      description: 'Follow curated learning paths from beginner to advanced mastery.',
    },
  ];

  const stats = [
    { label: 'Challenges', value: '1000+' },
    { label: 'Active Learners', value: '500+' },
    { label: 'Courses', value: '50+' },
    { label: 'Success Rate', value: '99%' },
  ];

  const steps = [
    { title: 'Choose a Course', desc: 'Pick a learning path that matches your goals.' },
    { title: 'Watch & Learn', desc: 'Study video tutorials and review materials.' },
    { title: 'Take Quizzes', desc: 'Test your knowledge with AI-generated quizzes.' },
    { title: 'Solve Challenges', desc: 'Write real code and get instant feedback.' },
  ];

  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-purple-50 to-transparent" />
        <div className="relative mx-auto max-w-5xl px-4 pb-20 pt-16 text-center md:pt-24 md:pb-28">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-purple-200 bg-purple-50 px-4 py-1.5 text-xs font-medium text-purple-600">
            <Sparkles className="h-3.5 w-3.5" />
            Learn to code with AI
          </div>

          <h1 className="text-4xl font-bold leading-tight text-gray-900 md:text-5xl lg:text-6xl">
            Level Up Your
            <br />
            <span className="text-purple-600">Coding Skills</span>
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-lg text-gray-500">
            Start your coding journey with AI-generated challenges, earn XP,
            solve real problems, and track your progress on the global leaderboard.
          </p>

          <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
            {loading ? (
              <div className="h-11 w-40 animate-pulse rounded-md bg-gray-200" />
            ) : user ? (
              <>
                <Button
                  size="lg"
                  onClick={() => router.push('/dashboard')}
                  className="w-full bg-purple-600 text-white hover:bg-purple-500 sm:w-auto"
                >
                  <Zap className="mr-2 h-4 w-4" />
                  Go to Dashboard
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  onClick={() => router.push('/my-courses')}
                  className="w-full border-gray-200 text-gray-900 hover:bg-gray-100 sm:w-auto"
                >
                  My Courses
                </Button>
              </>
            ) : (
              <>
                <Button
                  size="lg"
                  onClick={() => router.push('/auth/signup')}
                  className="w-full bg-purple-600 text-white hover:bg-purple-500 sm:w-auto"
                >
                  Get Started Free
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  onClick={() => router.push('/auth/login')}
                  className="w-full border-gray-200 text-gray-900 hover:bg-gray-100 sm:w-auto"
                >
                  Sign In
                </Button>
              </>
            )}
          </div>

          {/* Quick highlights */}
          <div className="mx-auto mt-12 grid max-w-3xl grid-cols-1 gap-3 md:grid-cols-3">
            {[
              { icon: <Code className="h-4 w-4 text-purple-600" />, text: 'Live Code Editor' },
              { icon: <BarChart3 className="h-4 w-4 text-purple-600" />, text: 'Global Ranking' },
              { icon: <GraduationCap className="h-4 w-4 text-purple-600" />, text: 'Expert Courses' },
            ].map((item) => (
              <div
                key={item.text}
                className="flex items-center justify-center gap-2 rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-600"
              >
                {item.icon}
                <span>{item.text}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="border-y border-gray-200 bg-gray-50/50">
        <div className="mx-auto max-w-5xl px-4 py-10">
          <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
            {stats.map((stat) => (
              <div key={stat.label} className="text-center">
                <p className="text-3xl font-bold text-gray-900">{stat.value}</p>
                <p className="mt-1 text-sm text-gray-500">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-5xl px-4 py-20">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold text-gray-900">Everything You Need to Learn</h2>
          <p className="mt-3 text-gray-500">Build your skills with focused training modules.</p>
        </div>

        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="rounded-xl border border-gray-200 bg-gray-50 p-6 transition-colors hover:border-gray-300"
            >
              <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-purple-50">
                {feature.icon}
              </div>
              <h3 className="mb-2 text-lg font-semibold text-gray-900">{feature.title}</h3>
              <p className="text-sm leading-relaxed text-gray-500">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="border-t border-gray-200 bg-gray-50/50 py-20">
        <div className="mx-auto max-w-5xl px-4">
          <div className="mb-12 text-center">
            <h2 className="text-3xl font-bold text-gray-900">How It Works</h2>
            <p className="mt-3 text-gray-500">Your roadmap to becoming an expert developer.</p>
          </div>

          <div className="grid grid-cols-1 gap-6 md:grid-cols-4">
            {steps.map((step, i) => (
              <div key={step.title} className="relative text-center">
                <div className="mx-auto mb-4 flex h-10 w-10 items-center justify-center rounded-full border border-purple-200 bg-purple-50 text-sm font-bold text-purple-600">
                  {i + 1}
                </div>
                <h3 className="mb-2 text-base font-semibold text-gray-900">{step.title}</h3>
                <p className="text-sm text-gray-500">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-5xl px-4 py-20">
        <div className="rounded-2xl border border-gray-200 bg-gray-50 px-6 py-12 text-center sm:px-12">
          {user ? (
            <>
              <h2 className="text-3xl font-bold text-gray-900">Welcome Back!</h2>
              <p className="mt-3 max-w-xl mx-auto text-gray-500">
                Keep building momentum, {user.full_name?.split(' ')[0] || 'Learner'}.
              </p>
              <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
                <Button
                  size="lg"
                  className="w-full bg-purple-600 text-white hover:bg-purple-500 sm:w-auto"
                  onClick={() => router.push('/dashboard')}
                >
                  Open Dashboard
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  className="w-full border-gray-200 text-gray-900 hover:bg-gray-100 sm:w-auto"
                  onClick={() => router.push('/practice')}
                >
                  Practice Now
                </Button>
              </div>
            </>
          ) : (
            <>
              <h2 className="text-3xl font-bold text-gray-900">Ready to Start?</h2>
              <p className="mt-3 max-w-xl mx-auto text-gray-500">
                Join thousands of learners improving their coding skills every day.
              </p>
              <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
                <Button
                  size="lg"
                  className="w-full bg-purple-600 text-white hover:bg-purple-500 sm:w-auto"
                  onClick={() => router.push('/auth/signup')}
                >
                  Get Started Free
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  className="w-full border-gray-200 text-gray-900 hover:bg-gray-100 sm:w-auto"
                  onClick={() => router.push('/courses')}
                >
                  Explore Courses
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </div>
            </>
          )}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-200 py-8">
        <div className="mx-auto flex max-w-5xl flex-col items-center justify-between gap-4 px-4 text-sm text-gray-400 md:flex-row">
          <div className="flex items-center gap-2">
            <div className="flex h-6 w-6 items-center justify-center rounded bg-purple-600">
              <Zap className="h-3 w-3 text-white" />
            </div>
            <span>© 2026 CodeZapra</span>
          </div>
          <div className="flex items-center gap-6">
            <Link href="#" className="hover:text-gray-900">Privacy</Link>
            <Link href="#" className="hover:text-gray-900">Terms</Link>
            <Link href="#" className="hover:text-gray-900">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
