'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Orbitron, Rajdhani } from 'next/font/google';
import { getCurrentUser } from '@/lib/auth';
import { Button } from '@/components/ui/button';
import {
  Swords,
  Sparkles,
  Code,
  Trophy,
  GraduationCap,
  ShieldCheck,
  Terminal,
  School,
  Zap,
  BarChart3,
  Flame,
  ArrowRight,
} from 'lucide-react';

const orbitron = Orbitron({ subsets: ['latin'], weight: ['500', '700', '900'] });
const rajdhani = Rajdhani({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export default function HomePage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadUser();
  }, []);

  const loadUser = async () => {
    try {
      const currentUser = await getCurrentUser();
      setUser(currentUser);
    } catch {
      setUser(null);
    } finally {
      setLoading(false);
    }
  };

  const features = [
    {
      icon: <Sparkles className="h-6 w-6 text-cyan-400" />,
      title: 'AI Sensei Integration',
      description: 'Dynamic quizzes generated by the System, adapting to your power level in real time.',
      rarity: 'RARE',
      rarityClass: 'text-cyan-300 border-cyan-400/60',
      hover: 'card-glow',
    },
    {
      icon: <Terminal className="h-6 w-6 text-purple-400" />,
      title: 'Hands-On Combat',
      description: 'Enter the dungeon editor, execute solutions, and receive instant system feedback.',
      rarity: 'EPIC',
      rarityClass: 'text-purple-300 border-purple-500/60',
      hover: 'card-epic',
    },
    {
      icon: <Trophy className="h-6 w-6 text-yellow-400" />,
      title: 'Ranked Ladder',
      description: 'Earn XP, rise through hunter ranks, and dominate the national leaderboard.',
      rarity: 'LEGENDARY',
      rarityClass: 'text-yellow-300 border-yellow-500/60',
      hover: 'card-legendary',
    },
    {
      icon: <School className="h-6 w-6 text-cyan-400" />,
      title: 'Structured Paths',
      description: 'Follow curated quest lines from novice to monarch-level mastery.',
      rarity: 'RARE',
      rarityClass: 'text-cyan-300 border-cyan-400/60',
      hover: 'card-glow',
    },
  ];

  const stats = [
    { label: 'Dungeons Cleared', value: '1000+' },
    { label: 'Active Hunters', value: '500+' },
    { label: 'Skill Books', value: '50+' },
    { label: 'Survival Rate', value: '99%' },
  ];

  const systemHighlights = [
    { icon: <ShieldCheck className="h-4 w-4 text-cyan-400" />, text: 'S-Rank Challenges' },
    { icon: <Code className="h-4 w-4 text-purple-400" />, text: 'Live Dungeon Editor' },
    { icon: <BarChart3 className="h-4 w-4 text-yellow-400" />, text: 'National Ranking' },
  ];

  const progression = [
    { title: 'Choose Your Class', desc: 'Select your class path based on your coding affinity.' },
    { title: 'Analyze Scrolls', desc: 'Watch tutorials and read system docs before battle.' },
    { title: 'Gate Trials', desc: 'Clear AI-generated quizzes to unlock combat stages.' },
    { title: 'Slay The Boss', desc: 'Defeat coding bosses to earn massive XP and titles.' },
  ];

  return (
    <div className={`${rajdhani.className} relative min-h-screen overflow-x-hidden`}>
      <div className="pointer-events-none absolute inset-0 opacity-70 hunter-grid-bg" />
      <div className="pointer-events-none absolute left-1/2 top-40 h-[420px] w-[900px] -translate-x-1/2 rounded-full bg-purple-600/20 blur-[120px]" />

      <section className="relative container px-4 pt-14 pb-20 md:pt-24 md:pb-28">
        <div className="mx-auto max-w-5xl text-center space-y-8">
          <div className="inline-flex items-center gap-2 rounded-full border border-purple-500/30 bg-purple-900/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">
            <Sparkles className="h-3.5 w-3.5" />
            System Awakened
          </div>

          <h1
            className={`${orbitron.className} hunter-glow-text text-4xl font-black leading-tight tracking-wide text-transparent bg-clip-text bg-gradient-to-r from-white via-purple-200 to-purple-400 md:text-6xl lg:text-7xl`}
          >
            LEVEL UP YOUR RANK:<br />
            THE HUNTER&apos;S CODE
          </h1>

          <p className="mx-auto max-w-3xl text-lg text-muted-foreground md:text-xl">
            Accept the quest to master coding. Enter AI-generated dungeons, earn XP,
            defeat bugs, and climb the global hunter rankings.
          </p>

          <div className="flex w-full flex-col items-center justify-center gap-3 sm:flex-row">
            {loading ? (
              <div className="h-10 w-40 bg-muted animate-pulse rounded-md" />
            ) : user ? (
              <>
                <Button
                  size="lg"
                  onClick={() => router.push('/dashboard')}
                  className={`${orbitron.className} btn-hunter h-12 w-full rounded-none border border-white/40 bg-white px-8 text-xs font-bold uppercase tracking-[0.2em] text-black hover:bg-white/90 sm:w-auto`}
                >
                  <Zap className="mr-2 h-4 w-4" />
                  Start Quest
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  onClick={() => router.push('/my-courses')}
                  className={`${orbitron.className} btn-hunter h-12 w-full rounded-none border border-white/30 bg-transparent px-8 text-xs font-bold uppercase tracking-[0.2em] text-white hover:border-purple-400 hover:text-purple-300 sm:w-auto`}
                >
                  View Guilds
                </Button>
              </>
            ) : (
              <>
                <Button
                  size="lg"
                  onClick={() => router.push('/auth/signup')}
                  className={`${orbitron.className} btn-hunter h-12 w-full rounded-none border border-white/40 bg-white px-8 text-xs font-bold uppercase tracking-[0.2em] text-black hover:bg-white/90 sm:w-auto`}
                >
                  <Swords className="mr-2 h-4 w-4" />
                  Accept Mission
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  onClick={() => router.push('/auth/login')}
                  className={`${orbitron.className} btn-hunter h-12 w-full rounded-none border border-white/30 bg-transparent px-8 text-xs font-bold uppercase tracking-[0.2em] text-white hover:border-purple-400 hover:text-purple-300 sm:w-auto`}
                >
                  System Initialize
                </Button>
              </>
            )}
          </div>

          <div className="mx-auto grid max-w-4xl grid-cols-1 gap-4 text-left md:grid-cols-3">
            {systemHighlights.map((item) => (
              <div
                key={item.text}
                className="group flex items-center gap-3 border border-white/10 bg-black/40 p-4 backdrop-blur-sm transition-colors hover:border-purple-400/50"
              >
                {item.icon}
                <span className={`${orbitron.className} text-xs font-semibold tracking-wide text-white/90`}>
                  {item.text}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="relative border-y border-white/10 bg-black/60">
        <div className="container px-4 py-10">
          <div className="grid grid-cols-2 gap-6 md:grid-cols-4 md:divide-x md:divide-white/10 md:gap-0">
            {stats.map((stat) => (
              <div key={stat.label} className="text-center md:px-4">
                <div className={`${orbitron.className} text-3xl font-bold text-white md:text-4xl`}>
                  {stat.value}
                </div>
                <div className="mt-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="relative container px-4 py-24">
        <div className="mb-14 text-center">
          <h2 className={`${orbitron.className} text-3xl font-bold text-white md:text-4xl`}>CHOOSE YOUR CLASS</h2>
          <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
            Analyze your potential and awaken your abilities with specialized training modules.
          </p>
        </div>

        <div className="mx-auto grid max-w-6xl grid-cols-1 gap-6 md:grid-cols-2">
          {features.map((feature) => (
            <div
              key={feature.title}
              className={`group relative border border-white/10 bg-black/50 p-8 backdrop-blur-sm transition-all duration-300 ${feature.hover}`}
            >
              <div className="absolute right-3 top-3">
                <span
                  className={`${orbitron.className} ${feature.rarityClass} inline-flex border px-2 py-1 text-[10px] font-bold tracking-[0.14em]`}
                >
                  {feature.rarity}
                </span>
              </div>

              <div className="mb-6 flex h-12 w-12 items-center justify-center rounded-md bg-white/5">
                {feature.icon}
              </div>

              <h3 className={`${orbitron.className} mb-3 text-xl font-bold text-white`}>{feature.title}</h3>
              <p className="text-sm leading-relaxed text-muted-foreground">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="relative bg-gradient-to-b from-transparent to-black/70 py-24">
        <div className="container px-4">
          <div className="mb-20 text-center">
            <h2 className={`${orbitron.className} text-3xl font-bold text-white md:text-4xl`}>QUEST PROGRESSION</h2>
            <p className="mt-3 text-muted-foreground">Your roadmap to becoming a Monarch.</p>
          </div>

          <div className="relative mx-auto max-w-4xl">
            <div className="absolute left-4 top-0 h-full w-px bg-white/15 md:left-1/2 md:-translate-x-1/2" />
            <div className="space-y-12 md:space-y-14">
              {progression.map((item, index) => {
                const odd = index % 2 === 0;
                return (
                  <div key={item.title} className="relative md:grid md:grid-cols-2 md:items-center">
                    <div className={`${odd ? 'md:pr-14 md:text-right' : 'md:order-2 md:pl-14'} pl-12 md:pl-0`}>
                      <h3 className={`${orbitron.className} text-2xl font-bold text-white`}>{item.title}</h3>
                      <p className="mt-2 text-sm text-muted-foreground">{item.desc}</p>
                    </div>
                    <div className={`${odd ? 'hidden md:block' : 'md:order-1'}`} />
                    <div className="absolute left-4 top-1.5 -translate-x-1/2 md:left-1/2 md:top-1/2 md:-translate-y-1/2">
                      <div className="quest-marker flex h-9 w-9 items-center justify-center rounded-full border border-cyan-400/70 bg-black text-sm font-bold text-cyan-300">
                        {index + 1}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      <section className="relative container px-4 py-24">
        <div className="mx-auto max-w-4xl rounded-2xl bg-gradient-to-r from-white/10 via-purple-500/30 to-white/10 p-[1px]">
          <div className="rounded-2xl border border-white/10 bg-black/80 px-6 py-12 text-center sm:px-10">
          {user ? (
            <>
              <h2 className={`${orbitron.className} text-4xl font-black text-white md:text-5xl`}>
                HUNTER STATUS: ACTIVE
              </h2>
              <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
                Welcome back, {user.full_name?.split(' ')[0] || 'Hunter'}. Continue your ascent.
              </p>
              <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
                <Button
                  size="lg"
                  className={`${orbitron.className} btn-hunter h-12 w-full rounded-none border border-white/40 bg-white px-8 text-xs font-bold uppercase tracking-[0.2em] text-black hover:bg-white/90 sm:w-auto`}
                  onClick={() => router.push('/dashboard')}
                >
                  Open Status Window
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  className={`${orbitron.className} btn-hunter h-12 w-full rounded-none border border-white/30 bg-transparent px-8 text-xs font-bold uppercase tracking-[0.2em] text-white hover:border-purple-400 hover:text-purple-300 sm:w-auto`}
                  onClick={() => router.push('/practice')}
                >
                  Enter Dungeon
                </Button>
              </div>
            </>
          ) : (
            <>
              <h2 className={`${orbitron.className} text-4xl font-black text-white md:text-5xl`}>READY TO AWAKEN?</h2>
              <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
                Join thousands of hunters mastering code. The System is waiting for you.
              </p>
              <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
                <Button
                  size="lg"
                  className={`${orbitron.className} btn-hunter h-12 w-full rounded-none border border-white/40 bg-white px-8 text-xs font-bold uppercase tracking-[0.2em] text-black hover:bg-white/90 sm:w-auto`}
                  onClick={() => router.push('/auth/signup')}
                >
                  Accept Mission
              </Button>
                <Button
                  size="lg"
                  className={`${orbitron.className} btn-hunter h-12 w-full rounded-none border border-white/30 bg-transparent px-8 text-xs font-bold uppercase tracking-[0.2em] text-white hover:border-purple-400 hover:text-purple-300 sm:w-auto`}
                  variant="outline"
                  onClick={() => router.push('/courses')}
                >
                  View Loot Table
                  <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
              </div>
            </>
          )}
          </div>
        </div>
      </section>

      <footer className="border-t border-white/10 bg-black/90 py-8">
        <div className="container flex flex-col items-center justify-between gap-4 px-4 text-sm text-muted-foreground md:flex-row">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded bg-purple-600">
              <Flame className="h-4 w-4 text-white" />
            </div>
            <span>© 2026 Levelup-Labs Hunter Association</span>
          </div>
          <div className="flex items-center gap-6">
            <Link href="#" className="hover:text-purple-300">Privacy</Link>
            <Link href="#" className="hover:text-purple-300">Terms</Link>
            <Link href="#" className="hover:text-purple-300">Contact Guild</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

