'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { getCurrentUser } from '@/lib/auth';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Trophy, Code, Zap, Target, Sparkles, GraduationCap } from 'lucide-react';

export default function HomePage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadUser();
  }, []);

  const loadUser = async () => {
    const currentUser = await getCurrentUser();
    setUser(currentUser);
    setLoading(false);
  };

  const features = [
    {
      icon: <Sparkles className="h-8 w-8 text-cyan-500" />,
      title: 'AI-Powered Learning',
      description: 'Dynamic quizzes and problems generated by Gemini AI tailored to your progress',
    },
    {
      icon: <Code className="h-8 w-8 text-purple-500" />,
      title: 'Hands-On Coding',
      description: 'Solve real problems with our interactive code editor and instant feedback',
    },
    {
      icon: <Trophy className="h-8 w-8 text-yellow-500" />,
      title: 'Gamified Experience',
      description: 'Earn points, climb the leaderboard, and compete with fellow coders',
    },
    {
      icon: <Target className="h-8 w-8 text-green-500" />,
      title: 'Structured Courses',
      description: 'Follow curated learning paths from basics to advanced topics',
    },
  ];

  const stats = [
    { label: 'AI-Generated Problems', value: '1000+' },
    { label: 'Active Learners', value: '500+' },
    { label: 'Course Modules', value: '50+' },
    { label: 'Success Rate', value: '92%' },
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="container px-4 py-20 md:py-32">
        <div className="mx-auto max-w-4xl text-center space-y-8">
          <div className="inline-flex items-center rounded-full border border-muted-foreground/20 px-4 py-1.5 text-sm bg-muted/40">
            <Sparkles className="mr-2 h-4 w-4 text-cyan-300" />
            <span>Powered by Gemini AI</span>
          </div>
          
          <h1 className="text-4xl font-bold tracking-tight sm:text-6xl text-foreground">
            Master Coding with AI-Powered Learning
          </h1>
          
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Learn to code through interactive courses, AI-generated challenges, and gamified experiences. 
            Track your progress, earn rewards, and compete on the leaderboard.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            {loading ? (
              <div className="h-10 w-40 bg-muted animate-pulse rounded-md" />
            ) : user ? (
              <>
                <Button size="lg" onClick={() => router.push('/courses')} className="min-w-[200px]">
                  <GraduationCap className="mr-2 h-5 w-5" />
                  Browse Courses
                </Button>
                <Button size="lg" variant="outline" onClick={() => router.push('/my-courses')} className="min-w-[200px]">
                  Continue Learning
                </Button>
              </>
            ) : (
              <>
                <Button size="lg" onClick={() => router.push('/auth/signup')} className="min-w-[200px]">
                  <Zap className="mr-2 h-5 w-5" />
                  Get Started Free
                </Button>
                <Button size="lg" variant="outline" onClick={() => router.push('/auth/login')} className="min-w-[200px]">
                  Sign In
                </Button>
              </>
            )}
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="container px-4 py-12 border-y">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          {stats.map((stat, index) => (
            <div key={index} className="text-center space-y-2">
              <div className="text-3xl md:text-4xl font-bold text-foreground">
                {stat.value}
              </div>
              <div className="text-sm text-muted-foreground">{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features Section */}
      <section className="container px-4 py-20">
        <div className="text-center space-y-4 mb-12">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Why Choose Levelup-Labs?
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Experience the future of coding education with AI-powered personalization and gamification
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 gap-6 max-w-5xl mx-auto">
          {features.map((feature, index) => (
            <Card key={index} className="border-2 hover:border-primary/50 transition-colors">
              <CardHeader>
                <div className="mb-4">{feature.icon}</div>
                <CardTitle>{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-base">{feature.description}</CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* How It Works */}
      <section className="container px-4 py-20 bg-muted/40">
        <div className="text-center space-y-4 mb-12">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Your Learning Journey
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Follow a structured path from beginner to expert
          </p>
        </div>
        
        <div className="grid md:grid-cols-4 gap-6 max-w-6xl mx-auto">
          {[
            { step: '1', title: 'Choose Course', desc: 'Select from our curated courses' },
            { step: '2', title: 'Watch & Learn', desc: 'Follow video tutorials and documentation' },
            { step: '3', title: 'Take Quizzes', desc: 'Test your knowledge with AI-generated quizzes' },
            { step: '4', title: 'Solve Problems', desc: 'Code solutions and earn points' },
          ].map((item, index) => (
            <div key={index} className="text-center space-y-3">
              <div className="mx-auto w-12 h-12 rounded-full bg-neutral-900 border border-neutral-700 flex items-center justify-center text-cyan-300 font-bold text-xl">
                {item.step}
              </div>
              <h3 className="font-semibold">{item.title}</h3>
              <p className="text-sm text-muted-foreground">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      {!user && (
        <section className="container px-4 py-20">
          <Card className="max-w-3xl mx-auto border border-neutral-800 bg-card/80">
            <CardHeader className="text-center space-y-4 pb-8">
              <CardTitle className="text-3xl">Ready to Start Your Journey?</CardTitle>
              <CardDescription className="text-lg">
                Join thousands of learners mastering code with AI-powered education
              </CardDescription>
            </CardHeader>
            <CardContent className="flex justify-center gap-4">
              <Button size="lg" onClick={() => router.push('/auth/signup')}>
                Create Free Account
              </Button>
              <Button size="lg" variant="outline" onClick={() => router.push('/courses')}>
                Explore Courses
              </Button>
            </CardContent>
          </Card>
        </section>
      )}
    </div>
  );
}
